const DataProducts = [
  {
    id: "1",
    nome: "Anel de prata pura ",
    image: "../imagens/AnelPrateado.png",
    imageVariation: "../imagens/imgVariation.png",
    price: "189,00",
    discount: "10",
    category: "aneis",
  },
  {
    id: "2",
    nome: "Anel flow duo banhado a ouro 18k e ródio",
    image: "../imagens/AnelDourado.png",
    imageVariation: "../imagens/imgVariation.png",
    price: "150,00",
    discount: "10",
    category: "aneis",
  },
  {
    id: "3",
    nome: "Colar flow banhado a ouro 18k",
    image: "../imagens/CorrenteDourada.png",
    imageVariation: "../imagens/imgVariation.png",
    price: "350,00",
    discount: "10",
    category: "colares",
  },
  {
    id: "4",
    nome: "Brincos banhados a ouro 18k",
    image: "../imagens/BrincosDourados.png",
    imageVariation: "../imagens/imgVariation.png",
    price: "220,00",
    discount: "10",
    category: "brincos",
  },
  {
    id: "5",
    nome: "Colar de ouro puro 18k ",
    image: "../imagens/ColarOuroPuro.png",
    imageVariation: "../imagens/imgVariation.png",
    price: "200,00",
    discount: "10",
    category: "colares",
  },
  {
    id: "6",
    nome: "Colar de prata pura",
    image: "../imagens/ColarPrataPura.png",
    imageVariation: "../imagens/imgVariation.png",
    price: "245,00",
    discount: "10",
    category: "colares",
  },
  {
    id: "7",
    nome: "Colar banhado a ouro 24k",
    image: "../imagens/ColarBanhado.png",
    imageVariation: "../imagens/imgVariation.png",
    price: "450,00",
    discount: "10",
    category: "colares",
  },
  {
    id: "8",
    nome: "Colar feito de marmore kahara",
    image: "../imagens/ColarMarmore.png",
    imageVariation: "../imagens/imgVariation.png",
    price: "500,00",
    discount: "10",
    category: "colares",
  },
];

export default DataProducts;
